/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package g4s21p4gerh;

/**
 *
 * @author estef
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpContenido = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ISuma = new javax.swing.JMenuItem();
        IResta = new javax.swing.JMenuItem();
        IMultiplicacion = new javax.swing.JMenuItem();
        IDivision = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dpContenidoLayout = new javax.swing.GroupLayout(dpContenido);
        dpContenido.setLayout(dpContenidoLayout);
        dpContenidoLayout.setHorizontalGroup(
            dpContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        dpContenidoLayout.setVerticalGroup(
            dpContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        jMenu1.setText("Operaciones ");

        ISuma.setText("Suma");
        ISuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISumaActionPerformed(evt);
            }
        });
        jMenu1.add(ISuma);

        IResta.setText("Resta");
        IResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IRestaActionPerformed(evt);
            }
        });
        jMenu1.add(IResta);

        IMultiplicacion.setText("Multiplicacion");
        IMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IMultiplicacionActionPerformed(evt);
            }
        });
        jMenu1.add(IMultiplicacion);

        IDivision.setText("Division");
        IDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDivisionActionPerformed(evt);
            }
        });
        jMenu1.add(IDivision);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Acerca de ");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ISumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISumaActionPerformed
        // TODO add your handling code here:
        FrmSuma frmsuma = new FrmSuma();
        frmsuma.setVisible(true);
        dpContenido.add(frmsuma);
    }//GEN-LAST:event_ISumaActionPerformed

    private void IRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IRestaActionPerformed
        // TODO add your handling code here:
        FrmResta frmresta = new FrmResta();
        frmresta.setVisible(true);
        dpContenido.add(frmresta);
    }//GEN-LAST:event_IRestaActionPerformed

    private void IMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IMultiplicacionActionPerformed
        // TODO add your handling code here:
        FrmMultiplicacion frmmulti = new FrmMultiplicacion();
        frmmulti.setVisible(true);
        dpContenido.add(frmmulti);
    }//GEN-LAST:event_IMultiplicacionActionPerformed

    private void IDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDivisionActionPerformed
        // TODO add your handling code here:
        FrmDivision frmdiv = new FrmDivision();
        frmdiv.setVisible(true);
        dpContenido.add(frmdiv);
    }//GEN-LAST:event_IDivisionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem IDivision;
    private javax.swing.JMenuItem IMultiplicacion;
    private javax.swing.JMenuItem IResta;
    private javax.swing.JMenuItem ISuma;
    private javax.swing.JPanel dpContenido;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
